env:
  commonjs: true
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  no-restricted-syntax: off
  guard-for-in: off
  no-prototype-builtins: off
  no-console: off
  no-continue: off
